#
# Apache Guacamole with NGINX reverse proxy and Let's Encrypt.
# 
version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  oznu-guacamole:
    image: oznu/guacamole
    container_name: oznu-guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      EXTENSIONS: auth-totp
      LETSENCRYPT_TEST: ${LETSENCRYPT_TEST:-false}
      VIRTUAL_HOST: 
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: 
    volumes:
      - guacconfig:/config

volumes:
  conf:
  vhost:
  html:
  certs:
  guacconfig:
